<?php
namespace Nes\Cpu;

class OpCode
{
    public static $cycles;
    public static $m;

    public static function getOpCodes()
    {
        self::$cycles = [
            7, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 4, 4, 6, 6,
            2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 6, 7,
            6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 4, 4, 6, 6,
            2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 6, 7,
            6, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 3, 4, 6, 6,
            2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 6, 7,
            6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 5, 4, 6, 6,
            2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 6, 7,
            2, 6, 2, 6, 3, 3, 3, 3, 2, 2, 2, 2, 4, 4, 4, 4,
            2, 6, 2, 6, 4, 4, 4, 4, 2, 4, 2, 5, 5, 4, 5, 5,
            2, 6, 2, 6, 3, 3, 3, 3, 2, 2, 2, 2, 4, 4, 4, 4,
            2, 5, 2, 5, 4, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 4,
            2, 6, 2, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6,
            2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,
            2, 6, 3, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6,
            2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,
        ];

        // @codingStandardsIgnoreStart
        return [
            'A9' => new OpCodeProps('LDA_IMM', 'LDA', new Addressing(Addressing::Immediate), self::$cycles[0xA9]),
            'A5' => new OpCodeProps('LDA_ZERO', 'LDA', new Addressing(Addressing::ZeroPage), self::$cycles[0xA5]),
            'AD' => new OpCodeProps('LDA_ABS', 'LDA', new Addressing(Addressing::Absolute), self::$cycles[0xAD]),
            'B5' => new OpCodeProps('LDA_ZEROX', 'LDA', new Addressing(Addressing::ZeroPageX), self::$cycles[0xB5]),
            'BD' => new OpCodeProps('LDA_ABSX', 'LDA', new Addressing(Addressing::AbsoluteX), self::$cycles[0xBD]),
            'B9' => new OpCodeProps('LDA_ABSY', 'LDA', new Addressing(Addressing::AbsoluteY), self::$cycles[0xB9]),
            'A1' => new OpCodeProps('LDA_INDX', 'LDA', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0xA1]),
            'B1' => new OpCodeProps('LDA_INDY', 'LDA', new Addressing(Addressing::PostIndexedIndirect), self::$cycles[0xB1]),
            'A2' => new OpCodeProps('LDX_IMM', 'LDX', new Addressing(Addressing::Immediate), self::$cycles[0xA2]),
            'A6' => new OpCodeProps('LDX_ZERO', 'LDX', new Addressing(Addressing::ZeroPage), self::$cycles[0xA6]),
            'AE' => new OpCodeProps('LDX_ABS', 'LDX', new Addressing(Addressing::Absolute), self::$cycles[0xAE]),
            'B6' => new OpCodeProps('LDX_ZEROY', 'LDX', new Addressing(Addressing::ZeroPageY), self::$cycles[0xB6]),
            'BE' => new OpCodeProps('LDX_ABSY', 'LDX', new Addressing(Addressing::AbsoluteY), self::$cycles[0xBE]),
            'A0' => new OpCodeProps('LDY_IMM', 'LDY', new Addressing(Addressing::Immediate), self::$cycles[0xA0]),
            'A4' => new OpCodeProps('LDY_ZERO', 'LDY', new Addressing(Addressing::ZeroPage), self::$cycles[0xA4]),
            'AC' => new OpCodeProps('LDY_ABS', 'LDY', new Addressing(Addressing::Absolute), self::$cycles[0xAC]),
            'B4' => new OpCodeProps('LDY_ZEROX', 'LDY', new Addressing(Addressing::ZeroPageX), self::$cycles[0xB4]),
            'BC' => new OpCodeProps('LDY_ABSX', 'LDY', new Addressing(Addressing::AbsoluteX), self::$cycles[0xBC]),
            '85' => new OpCodeProps('STA_ZERO', 'STA', new Addressing(Addressing::ZeroPage), self::$cycles[0x85]),
            '8D' => new OpCodeProps('STA_ABS', 'STA', new Addressing(Addressing::Absolute), self::$cycles[0x8D]),
            '95' => new OpCodeProps('STA_ZEROX', 'STA', new Addressing(Addressing::ZeroPageX), self::$cycles[0x95]),
            '9D' => new OpCodeProps('STA_ABSX', 'STA', new Addressing(Addressing::AbsoluteX), self::$cycles[0x9D]),
            '99' => new OpCodeProps('STA_ABSY', 'STA', new Addressing(Addressing::AbsoluteY), self::$cycles[0x99]),
            '81' => new OpCodeProps('STA_INDX', 'STA', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0x81]),
            '91' => new OpCodeProps('STA_INDY', 'STA', new Addressing(Addressing::PostIndexedIndirect), self::$cycles[0x91]),
            '86' => new OpCodeProps('STX_ZERO', 'STX', new Addressing(Addressing::ZeroPage), self::$cycles[0x86]),
            '8E' => new OpCodeProps('STX_ABS', 'STX', new Addressing(Addressing::Absolute), self::$cycles[0x8E]),
            '96' => new OpCodeProps('STX_ZEROY', 'STX', new Addressing(Addressing::ZeroPageY), self::$cycles[0x96]),
            '84' => new OpCodeProps('STY_ZERO', 'STY', new Addressing(Addressing::ZeroPage), self::$cycles[0x84]),
            '8C' => new OpCodeProps('STY_ABS', 'STY', new Addressing(Addressing::Absolute), self::$cycles[0x8C]),
            '94' => new OpCodeProps('STY_ZEROX', 'STY', new Addressing(Addressing::ZeroPageX), self::$cycles[0x94]),
            '8A' => new OpCodeProps('TXA', 'TXA', new Addressing(Addressing::Implied), self::$cycles[0x8A]),
            '98' => new OpCodeProps('TYA', 'TYA', new Addressing(Addressing::Implied), self::$cycles[0x98]),
            '9A' => new OpCodeProps('TXS', 'TXS', new Addressing(Addressing::Implied), self::$cycles[0x9A]),
            'A8' => new OpCodeProps('TAY', 'TAY', new Addressing(Addressing::Implied), self::$cycles[0xA8]),
            'AA' => new OpCodeProps('TAX', 'TAX', new Addressing(Addressing::Implied), self::$cycles[0xAA]),
            'BA' => new OpCodeProps('TSX', 'TSX', new Addressing(Addressing::Implied), self::$cycles[0xBA]),
            '8' => new OpCodeProps('PHP', 'PHP', new Addressing(Addressing::Implied), self::$cycles[0x08]),
            '28' => new OpCodeProps('PLP', 'PLP', new Addressing(Addressing::Implied), self::$cycles[0x28]),
            '48' => new OpCodeProps('PHA', 'PHA', new Addressing(Addressing::Implied), self::$cycles[0x48]),
            '68' => new OpCodeProps('PLA', 'PLA', new Addressing(Addressing::Implied), self::$cycles[0x68]),
            '69' => new OpCodeProps('ADC_IMM', 'ADC', new Addressing(Addressing::Immediate), self::$cycles[0x69]),
            '65' => new OpCodeProps('ADC_ZERO', 'ADC', new Addressing(Addressing::ZeroPage), self::$cycles[0x65]),
            '6D' => new OpCodeProps('ADC_ABS', 'ADC', new Addressing(Addressing::Absolute), self::$cycles[0x6D]),
            '75' => new OpCodeProps('ADC_ZEROX', 'ADC', new Addressing(Addressing::ZeroPageX), self::$cycles[0x75]),
            '7D' => new OpCodeProps('ADC_ABSX', 'ADC', new Addressing(Addressing::AbsoluteX), self::$cycles[0x7D]),
            '79' => new OpCodeProps('ADC_ABSY', 'ADC', new Addressing(Addressing::AbsoluteY), self::$cycles[0x79]),
            '61' => new OpCodeProps('ADC_INDX', 'ADC', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0x61]),
            '71' => new OpCodeProps('ADC_INDY', 'ADC', new Addressing(Addressing::PostIndexedIndirect), self::$cycles[0x71]),
            'E9' => new OpCodeProps('SBC_IMM', 'SBC', new Addressing(Addressing::Immediate), self::$cycles[0xE9]),
            'E5' => new OpCodeProps('SBC_ZERO', 'SBC', new Addressing(Addressing::ZeroPage), self::$cycles[0xE5]),
            'ED' => new OpCodeProps('SBC_ABS', 'SBC', new Addressing(Addressing::Absolute), self::$cycles[0xED]),
            'F5' => new OpCodeProps('SBC_ZEROX', 'SBC', new Addressing(Addressing::ZeroPageX), self::$cycles[0xF5]),
            'FD' => new OpCodeProps('SBC_ABSX', 'SBC', new Addressing(Addressing::AbsoluteX), self::$cycles[0xFD]),
            'F9' => new OpCodeProps('SBC_ABSY', 'SBC', new Addressing(Addressing::AbsoluteY), self::$cycles[0xF9]),
            'E1' => new OpCodeProps('SBC_INDX', 'SBC', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0xE1]),
            'F1' => new OpCodeProps('SBC_INDY', 'SBC', new Addressing(Addressing::PostIndexedIndirect), self::$cycles[0xF1]),
            'E0' => new OpCodeProps('CPX_IMM', 'CPX', new Addressing(Addressing::Immediate), self::$cycles[0xE0]),
            'E4' => new OpCodeProps('CPX_ZERO', 'CPX', new Addressing(Addressing::ZeroPage), self::$cycles[0xE4]),
            'EC' => new OpCodeProps('CPX_ABS', 'CPX', new Addressing(Addressing::Absolute), self::$cycles[0xEC]),
            'C0' => new OpCodeProps('CPY_IMM', 'CPY', new Addressing(Addressing::Immediate), self::$cycles[0xC0]),
            'C4' => new OpCodeProps('CPY_ZERO', 'CPY', new Addressing(Addressing::ZeroPage), self::$cycles[0xC4]),
            'CC' => new OpCodeProps('CPY_ABS', 'CPY', new Addressing(Addressing::Absolute), self::$cycles[0xCC]),
            'C9' => new OpCodeProps('CMP_IMM', 'CMP', new Addressing(Addressing::Immediate), self::$cycles[0xC9]),
            'C5' => new OpCodeProps('CMP_ZERO', 'CMP', new Addressing(Addressing::ZeroPage), self::$cycles[0xC5]),
            'CD' => new OpCodeProps('CMP_ABS', 'CMP', new Addressing(Addressing::Absolute), self::$cycles[0xCD]),
            'D5' => new OpCodeProps('CMP_ZEROX', 'CMP', new Addressing(Addressing::ZeroPageX), self::$cycles[0xD5]),
            'DD' => new OpCodeProps('CMP_ABSX', 'CMP', new Addressing(Addressing::AbsoluteX), self::$cycles[0xDD]),
            'D9' => new OpCodeProps('CMP_ABSY', 'CMP', new Addressing(Addressing::AbsoluteY), self::$cycles[0xD9]),
            'C1' => new OpCodeProps('CMP_INDX', 'CMP', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0xC1]),
            'D1' => new OpCodeProps('CMP_INDY', 'CMP', new Addressing(Addressing::PostIndexedIndirect), self::$cycles[0xD1]),
            '29' => new OpCodeProps('AND_IMM', 'AND', new Addressing(Addressing::Immediate), self::$cycles[0x29]),
            '25' => new OpCodeProps('AND_ZERO', 'AND', new Addressing(Addressing::ZeroPage), self::$cycles[0x25]),
            '2D' => new OpCodeProps('AND_ABS', 'AND', new Addressing(Addressing::Absolute), self::$cycles[0x2D]),
            '35' => new OpCodeProps('AND_ZEROX', 'AND', new Addressing(Addressing::ZeroPageX), self::$cycles[0x35]),
            '3D' => new OpCodeProps('AND_ABSX', 'AND', new Addressing(Addressing::AbsoluteX), self::$cycles[0x3D]),
            '39' => new OpCodeProps('AND_ABSY', 'AND', new Addressing(Addressing::AbsoluteY), self::$cycles[0x39]),
            '21' => new OpCodeProps('AND_INDX', 'AND', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0x21]),
            '31' => new OpCodeProps('AND_INDY', 'AND', new Addressing(Addressing::PostIndexedIndirect), self::$cycles[0x31]),
            '49' => new OpCodeProps('EOR_IMM', 'EOR', new Addressing(Addressing::Immediate), self::$cycles[0x49]),
            '45' => new OpCodeProps('EOR_ZERO', 'EOR', new Addressing(Addressing::ZeroPage), self::$cycles[0x45]),
            '4D' => new OpCodeProps('EOR_ABS', 'EOR', new Addressing(Addressing::Absolute), self::$cycles[0x4D]),
            '55' => new OpCodeProps('EOR_ZEROX', 'EOR', new Addressing(Addressing::ZeroPageX), self::$cycles[0x55]),
            '5D' => new OpCodeProps('EOR_ABSX', 'EOR', new Addressing(Addressing::AbsoluteX), self::$cycles[0x5D]),
            '59' => new OpCodeProps('EOR_ABSY', 'EOR', new Addressing(Addressing::AbsoluteY), self::$cycles[0x59]),
            '41' => new OpCodeProps('EOR_INDX', 'EOR', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0x41]),
            '51' => new OpCodeProps('EOR_INDY', 'EOR', new Addressing(Addressing::PostIndexedIndirect), self::$cycles[0x51]),
            '9' => new OpCodeProps('ORA_IMM', 'ORA', new Addressing(Addressing::Immediate), self::$cycles[0x09]),
            '5' => new OpCodeProps('ORA_ZERO', 'ORA', new Addressing(Addressing::ZeroPage), self::$cycles[0x05]),
            'D' => new OpCodeProps('ORA_ABS', 'ORA', new Addressing(Addressing::Absolute), self::$cycles[0x0D]),
            '15' => new OpCodeProps('ORA_ZEROX', 'ORA', new Addressing(Addressing::ZeroPageX), self::$cycles[0x15]),
            '1D' => new OpCodeProps('ORA_ABSX', 'ORA', new Addressing(Addressing::AbsoluteX), self::$cycles[0x1D]),
            '19' => new OpCodeProps('ORA_ABSY', 'ORA', new Addressing(Addressing::AbsoluteY), self::$cycles[0x19]),
            '1' => new OpCodeProps('ORA_INDX', 'ORA', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0x01]),
            '11' => new OpCodeProps('ORA_INDY', 'ORA', new Addressing(Addressing::PostIndexedIndirect), self::$cycles[0x11]),
            '24' => new OpCodeProps('BIT_ZERO', 'BIT', new Addressing(Addressing::ZeroPage), self::$cycles[0x24]),
            '2C' => new OpCodeProps('BIT_ABS', 'BIT', new Addressing(Addressing::Absolute), self::$cycles[0x2C]),
            'A' => new OpCodeProps('ASL', 'ASL', new Addressing(Addressing::Accumulator), self::$cycles[0x0A]),
            '6' => new OpCodeProps('ASL_ZERO', 'ASL', new Addressing(Addressing::ZeroPage), self::$cycles[0x06]),
            'E' => new OpCodeProps('ASL_ABS', 'ASL', new Addressing(Addressing::Absolute), self::$cycles[0x0E]),
            '16' => new OpCodeProps('ASL_ZEROX', 'ASL', new Addressing(Addressing::ZeroPageX), self::$cycles[0x16]),
            '1E' => new OpCodeProps('ASL_ABSX', 'ASL', new Addressing(Addressing::AbsoluteX), self::$cycles[0x1E]),
            '4A' => new OpCodeProps('LSR', 'LSR', new Addressing(Addressing::Accumulator), self::$cycles[0x4A]),
            '46' => new OpCodeProps('LSR_ZERO', 'LSR', new Addressing(Addressing::ZeroPage), self::$cycles[0x46]),
            '4E' => new OpCodeProps('LSR_ABS', 'LSR', new Addressing(Addressing::Absolute), self::$cycles[0x4E]),
            '56' => new OpCodeProps('LSR_ZEROX', 'LSR', new Addressing(Addressing::ZeroPageX), self::$cycles[0x56]),
            '5E' => new OpCodeProps('LSR_ABSX', 'LSR', new Addressing(Addressing::AbsoluteX), self::$cycles[0x5E]),
            '2A' => new OpCodeProps('ROL', 'ROL', new Addressing(Addressing::Accumulator), self::$cycles[0x2A]),
            '26' => new OpCodeProps('ROL_ZERO', 'ROL', new Addressing(Addressing::ZeroPage), self::$cycles[0x26]),
            '2E' => new OpCodeProps('ROL_ABS', 'ROL', new Addressing(Addressing::Absolute), self::$cycles[0x2E]),
            '36' => new OpCodeProps('ROL_ZEROX', 'ROL', new Addressing(Addressing::ZeroPageX), self::$cycles[0x36]),
            '3E' => new OpCodeProps('ROL_ABSX', 'ROL', new Addressing(Addressing::AbsoluteX), self::$cycles[0x3E]),
            '6A' => new OpCodeProps('ROR', 'ROR', new Addressing(Addressing::Accumulator), self::$cycles[0x6A]),
            '66' => new OpCodeProps('ROR_ZERO', 'ROR', new Addressing(Addressing::ZeroPage), self::$cycles[0x66]),
            '6E' => new OpCodeProps('ROR_ABS', 'ROR', new Addressing(Addressing::Absolute), self::$cycles[0x6E]),
            '76' => new OpCodeProps('ROR_ZEROX', 'ROR', new Addressing(Addressing::ZeroPageX), self::$cycles[0x76]),
            '7E' => new OpCodeProps('ROR_ABSX', 'ROR', new Addressing(Addressing::AbsoluteX), self::$cycles[0x7E]),
            'E8' => new OpCodeProps('INX', 'INX', new Addressing(Addressing::Implied), self::$cycles[0xE8]),
            'C8' => new OpCodeProps('INY', 'INY', new Addressing(Addressing::Implied), self::$cycles[0xC8]),
            'E6' => new OpCodeProps('INC_ZERO', 'INC', new Addressing(Addressing::ZeroPage), self::$cycles[0xE6]),
            'EE' => new OpCodeProps('INC_ABS', 'INC', new Addressing(Addressing::Absolute), self::$cycles[0xEE]),
            'F6' => new OpCodeProps('INC_ZEROX', 'INC', new Addressing(Addressing::ZeroPageX), self::$cycles[0xF6]),
            'FE' => new OpCodeProps('INC_ABSX', 'INC', new Addressing(Addressing::AbsoluteX), self::$cycles[0xFE]),
            'CA' => new OpCodeProps('DEX', 'DEX', new Addressing(Addressing::Implied), self::$cycles[0xCA]),
            '88' => new OpCodeProps('DEY', 'DEY', new Addressing(Addressing::Implied), self::$cycles[0x88]),
            'C6' => new OpCodeProps('DEC_ZERO', 'DEC', new Addressing(Addressing::ZeroPage), self::$cycles[0xC6]),
            'CE' => new OpCodeProps('DEC_ABS', 'DEC', new Addressing(Addressing::Absolute), self::$cycles[0xCE]),
            'D6' => new OpCodeProps('DEC_ZEROX', 'DEC', new Addressing(Addressing::ZeroPageX), self::$cycles[0xD6]),
            'DE' => new OpCodeProps('DEC_ABSX', 'DEC', new Addressing(Addressing::AbsoluteX), self::$cycles[0xDE]),
            '18' => new OpCodeProps('CLC', 'CLC', new Addressing(Addressing::Implied), self::$cycles[0x18]),
            '58' => new OpCodeProps('CLI', 'CLI', new Addressing(Addressing::Implied), self::$cycles[0x58]),
            'B8' => new OpCodeProps('CLV', 'CLV', new Addressing(Addressing::Implied), self::$cycles[0xB8]),
            '38' => new OpCodeProps('SEC', 'SEC', new Addressing(Addressing::Implied), self::$cycles[0x38]),
            '78' => new OpCodeProps('SEI', 'SEI', new Addressing(Addressing::Implied), self::$cycles[0x78]),
            'EA' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0xEA]),
            '0' => new OpCodeProps('BRK', 'BRK', new Addressing(Addressing::Implied), self::$cycles[0x00]),
            '20' => new OpCodeProps('JSR_ABS', 'JSR', new Addressing(Addressing::Absolute), self::$cycles[0x20]),
            '4C' => new OpCodeProps('JMP_ABS', 'JMP', new Addressing(Addressing::Absolute), self::$cycles[0x4C]),
            '6C' => new OpCodeProps('JMP_INDABS', 'JMP', new Addressing(Addressing::IndirectAbsolute), self::$cycles[0x6C]),
            '40' => new OpCodeProps('RTI', 'RTI', new Addressing(Addressing::Implied), self::$cycles[0x40]),
            '60' => new OpCodeProps('RTS', 'RTS', new Addressing(Addressing::Implied), self::$cycles[0x60]),
            '10' => new OpCodeProps('BPL', 'BPL', new Addressing(Addressing::Relative), self::$cycles[0x10]),
            '30' => new OpCodeProps('BMI', 'BMI', new Addressing(Addressing::Relative), self::$cycles[0x30]),
            '50' => new OpCodeProps('BVC', 'BVC', new Addressing(Addressing::Relative), self::$cycles[0x50]),
            '70' => new OpCodeProps('BVS', 'BVS', new Addressing(Addressing::Relative), self::$cycles[0x70]),
            '90' => new OpCodeProps('BCC', 'BCC', new Addressing(Addressing::Relative), self::$cycles[0x90]),
            'B0' => new OpCodeProps('BCS', 'BCS', new Addressing(Addressing::Relative), self::$cycles[0xB0]),
            'D0' => new OpCodeProps('BNE', 'BNE', new Addressing(Addressing::Relative), self::$cycles[0xD0]),
            'F0' => new OpCodeProps('BEQ', 'BEQ', new Addressing(Addressing::Relative), self::$cycles[0xF0]),
            'F8' => new OpCodeProps('SED', 'SED', new Addressing(Addressing::Implied), self::$cycles[0xF8]),
            'D8' => new OpCodeProps('CLD', 'CLD', new Addressing(Addressing::Implied), self::$cycles[0xD8]),
            // unofficial opecode
            // Also see https://wiki.nesdev.com/w/index.php/CPU_unofficial_opcodes
            '1A' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0x1A]),
            '3A' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0x3A]),
            '5A' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0x5A]),
            '7A' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0x7A]),
            'DA' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0xDA]),
            'FA' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0xFA]),

            '02' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0x02]),
            '12' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0x12]),
            '22' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0x22]),
            '32' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0x32]),
            '42' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0x42]),
            '52' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0x52]),
            '62' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0x62]),
            '72' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0x72]),
            '92' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0x92]),
            'B2' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0xB2]),
            'D2' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0xD2]),
            'F2' => new OpCodeProps('NOP', 'NOP', new Addressing(Addressing::Implied), self::$cycles[0xF2]),

            '80' => new OpCodeProps('NOPD', 'NOPD', new Addressing(Addressing::Implied), self::$cycles[0x80]),
            '82' => new OpCodeProps('NOPD', 'NOPD', new Addressing(Addressing::Implied), self::$cycles[0x82]),
            '89' => new OpCodeProps('NOPD', 'NOPD', new Addressing(Addressing::Implied), self::$cycles[0x89]),
            'C2' => new OpCodeProps('NOPD', 'NOPD', new Addressing(Addressing::Implied), self::$cycles[0xC2]),
            'E2' => new OpCodeProps('NOPD', 'NOPD', new Addressing(Addressing::Implied), self::$cycles[0xE2]),
            '04' => new OpCodeProps('NOPD', 'NOPD', new Addressing(Addressing::Implied), self::$cycles[0x04]),
            '44' => new OpCodeProps('NOPD', 'NOPD', new Addressing(Addressing::Implied), self::$cycles[0x44]),
            '64' => new OpCodeProps('NOPD', 'NOPD', new Addressing(Addressing::Implied), self::$cycles[0x64]),
            '14' => new OpCodeProps('NOPD', 'NOPD', new Addressing(Addressing::Implied), self::$cycles[0x14]),
            '34' => new OpCodeProps('NOPD', 'NOPD', new Addressing(Addressing::Implied), self::$cycles[0x34]),
            '54' => new OpCodeProps('NOPD', 'NOPD', new Addressing(Addressing::Implied), self::$cycles[0x54]),
            '74' => new OpCodeProps('NOPD', 'NOPD', new Addressing(Addressing::Implied), self::$cycles[0x74]),
            'D4' => new OpCodeProps('NOPD', 'NOPD', new Addressing(Addressing::Implied), self::$cycles[0xD4]),
            'F4' => new OpCodeProps('NOPD', 'NOPD', new Addressing(Addressing::Implied), self::$cycles[0xF4]),

            '0C' => new OpCodeProps('NOPI', 'NOPI', new Addressing(Addressing::Implied), self::$cycles[0x0C]),
            '1C' => new OpCodeProps('NOPI', 'NOPI', new Addressing(Addressing::Implied), self::$cycles[0x1C]),
            '3C' => new OpCodeProps('NOPI', 'NOPI', new Addressing(Addressing::Implied), self::$cycles[0x3C]),
            '5C' => new OpCodeProps('NOPI', 'NOPI', new Addressing(Addressing::Implied), self::$cycles[0x5C]),
            '7C' => new OpCodeProps('NOPI', 'NOPI', new Addressing(Addressing::Implied), self::$cycles[0x7C]),
            'DC' => new OpCodeProps('NOPI', 'NOPI', new Addressing(Addressing::Implied), self::$cycles[0xDC]),
            'FC' => new OpCodeProps('NOPI', 'NOPI', new Addressing(Addressing::Implied), self::$cycles[0xFC]),
            // LAX
            'A7' => new OpCodeProps('LAX_ZERO', 'LAX', new Addressing(Addressing::ZeroPage), self::$cycles[0xA7]),
            'B7' => new OpCodeProps('LAX_ZEROY', 'LAX', new Addressing(Addressing::ZeroPageY), self::$cycles[0xB7]),
            'AF' => new OpCodeProps('LAX_ABS', 'LAX', new Addressing(Addressing::Absolute), self::$cycles[0xAF]),
            'BF' => new OpCodeProps('LAX_ABSY', 'LAX', new Addressing(Addressing::AbsoluteY), self::$cycles[0xBF]),
            'A3' => new OpCodeProps('LAX_INDX', 'LAX', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0xA3]),
            'B3' => new OpCodeProps('LAX_INDY', 'LAX', new Addressing(Addressing::PostIndexedIndirect), self::$cycles[0xB3]),
            // SAX
            '87' => new OpCodeProps('SAX_ZERO', 'SAX', new Addressing(Addressing::ZeroPage), self::$cycles[0x87]),
            '97' => new OpCodeProps('SAX_ZEROY', 'SAX', new Addressing(Addressing::ZeroPageY), self::$cycles[0x97]),
            '8F' => new OpCodeProps('SAX_ABS', 'SAX', new Addressing(Addressing::Absolute), self::$cycles[0x8F]),
            '83' => new OpCodeProps('SAX_INDX', 'SAX', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0x83]),
            // SBC
            'EB' => new OpCodeProps('SBC_IMM', 'SBC', new Addressing(Addressing::Immediate), self::$cycles[0xEB]),
            // DCP
            'C7' => new OpCodeProps('DCP_ZERO', 'DCP', new Addressing(Addressing::ZeroPage), self::$cycles[0xC7]),
            'D7' => new OpCodeProps('DCP_ZEROX', 'DCP', new Addressing(Addressing::ZeroPageX), self::$cycles[0xD7]),
            'CF' => new OpCodeProps('DCP_ABS', 'DCP', new Addressing(Addressing::Absolute), self::$cycles[0xCF]),
            'DF' => new OpCodeProps('DCP_ABSX', 'DCP', new Addressing(Addressing::AbsoluteX), self::$cycles[0xDF]),
            'DB' => new OpCodeProps('DCP_ABSY', 'DCP', new Addressing(Addressing::AbsoluteY), self::$cycles[0xD8]),
            'C3' => new OpCodeProps('DCP_INDX', 'DCP', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0xC3]),
            'D3' => new OpCodeProps('DCP_INDY', 'DCP', new Addressing(Addressing::PostIndexedIndirect), self::$cycles[0xD3]),
            // ISB
            'E7' => new OpCodeProps('ISB_ZERO', 'ISB', new Addressing(Addressing::ZeroPage), self::$cycles[0xE7]),
            'F7' => new OpCodeProps('ISB_ZEROX', 'ISB', new Addressing(Addressing::ZeroPageX), self::$cycles[0xF7]),
            'EF' => new OpCodeProps('ISB_ABS', 'ISB', new Addressing(Addressing::Absolute), self::$cycles[0xEF]),
            'FF' => new OpCodeProps('ISB_ABSX', 'ISB', new Addressing(Addressing::AbsoluteX), self::$cycles[0xFF]),
            'FB' => new OpCodeProps('ISB_ABSY', 'ISB', new Addressing(Addressing::AbsoluteY), self::$cycles[0xF8]),
            'E3' => new OpCodeProps('ISB_INDX', 'ISB', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0xE3]),
            'F3' => new OpCodeProps('ISB_INDY', 'ISB', new Addressing(Addressing::PostIndexedIndirect), self::$cycles[0xF3]),
            // SLO
            '07' => new OpCodeProps('SLO_ZERO', 'SLO', new Addressing(Addressing::ZeroPage), self::$cycles[0x07]),
            '17' => new OpCodeProps('SLO_ZEROX', 'SLO', new Addressing(Addressing::ZeroPageX), self::$cycles[0x17]),
            '0F' => new OpCodeProps('SLO_ABS', 'SLO', new Addressing(Addressing::Absolute), self::$cycles[0x0F]),
            '1F' => new OpCodeProps('SLO_ABSX', 'SLO', new Addressing(Addressing::AbsoluteX), self::$cycles[0x1F]),
            '1B' => new OpCodeProps('SLO_ABSY', 'SLO', new Addressing(Addressing::AbsoluteY), self::$cycles[0x1B]),
            '03' => new OpCodeProps('SLO_INDX', 'SLO', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0x03]),
            '13' => new OpCodeProps('SLO_INDY', 'SLO', new Addressing(Addressing::PostIndexedIndirect), self::$cycles[0x13]),
            // RLA
            '27' => new OpCodeProps('RLA_ZERO', 'RLA', new Addressing(Addressing::ZeroPage), self::$cycles[0x27]),
            '37' => new OpCodeProps('RLA_ZEROX', 'RLA', new Addressing(Addressing::ZeroPageX), self::$cycles[0x37]),
            '2F' => new OpCodeProps('RLA_ABS', 'RLA', new Addressing(Addressing::Absolute), self::$cycles[0x2F]),
            '3F' => new OpCodeProps('RLA_ABSX', 'RLA', new Addressing(Addressing::AbsoluteX), self::$cycles[0x3F]),
            '3B' => new OpCodeProps('RLA_ABSY', 'RLA', new Addressing(Addressing::AbsoluteY), self::$cycles[0x3B]),
            '23' => new OpCodeProps('RLA_INDX', 'RLA', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0x23]),
            '33' => new OpCodeProps('RLA_INDY', 'RLA', new Addressing(Addressing::PostIndexedIndirect), self::$cycles[0x33]),
            // SRE
            '47' => new OpCodeProps('SRE_ZERO', 'SRE', new Addressing(Addressing::ZeroPage), self::$cycles[0x47]),
            '57' => new OpCodeProps('SRE_ZEROX', 'SRE', new Addressing(Addressing::ZeroPageX), self::$cycles[0x57]),
            '4F' => new OpCodeProps('SRE_ABS', 'SRE', new Addressing(Addressing::Absolute), self::$cycles[0x4F]),
            '5F' => new OpCodeProps('SRE_ABSX', 'SRE', new Addressing(Addressing::AbsoluteX), self::$cycles[0x5F]),
            '5B' => new OpCodeProps('SRE_ABSY', 'SRE', new Addressing(Addressing::AbsoluteY), self::$cycles[0x5B]),
            '43' => new OpCodeProps('SRE_INDX', 'SRE', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0x43]),
            '53' => new OpCodeProps('SRE_INDY', 'SRE', new Addressing(Addressing::PostIndexedIndirect), self::$cycles[0x53]),
            // RRA
            '67' => new OpCodeProps('RRA_ZERO', 'RRA', new Addressing(Addressing::ZeroPage), self::$cycles[0x67]),
            '77' => new OpCodeProps('RRA_ZEROX', 'RRA', new Addressing(Addressing::ZeroPageX), self::$cycles[0x77]),
            '6F' => new OpCodeProps('RRA_ABS', 'RRA', new Addressing(Addressing::Absolute), self::$cycles[0x6F]),
            '7F' => new OpCodeProps('RRA_ABSX', 'RRA', new Addressing(Addressing::AbsoluteX), self::$cycles[0x7F]),
            '7B' => new OpCodeProps('RRA_ABSY', 'RRA', new Addressing(Addressing::AbsoluteY), self::$cycles[0x7B]),
            '63' => new OpCodeProps('RRA_INDX', 'RRA', new Addressing(Addressing::PreIndexedIndirect), self::$cycles[0x63]),
            '73' => new OpCodeProps('RRA_INDY', 'RRA', new Addressing(Addressing::PostIndexedIndirect), self::$cycles[0x73]),
        ];
        // @codingStandardsIgnoreEnd
    }
}
